import pandas as pd
import numpy as np
import string
import re
from nltk.corpus import stopwords
nltk_stopwords = stopwords.words("english")+["rt", "via","-»","--»","--","---","-->","<--","->","<-","«--","«","«-","»","«»", " →", "→"]
remove_punctuaton = '!"$%&\'()*+,-./:;<=>?@[\\]“”^_`{|}~’'

emojis= re.compile("["
            u"\U0001F300-\U0001F5FF"  # symbols & pictographs
            u"\U0001F680-\U0001F6FF"  # transport & map symbols
            u"\U0001F1E0-\U0001F1FF"  # flags (iOS)
                               "]+", flags=re.UNICODE)

def add_leading_and_trailing_space(dataframe, column):
    dataframe[column] = ' ' + dataframe[column].astype(str)
    dataframe[column] = dataframe[column].astype(str) + ' '

def filtration_1(dataframe, column_to_clean, new_col):
    df = dataframe.copy()
    df[column_to_clean] = df[column_to_clean].str.lower()
    df[column_to_clean] = df[column_to_clean].apply(lambda x: x.replace(" he'll ", " he will "))
    df[column_to_clean] = df[column_to_clean].apply(lambda x: x.replace(" i'd ", " i would "))
    df[column_to_clean] = df[column_to_clean].apply(lambda x: x.replace(" i'll ", " i will "))
    df[column_to_clean] = df[column_to_clean].apply(lambda x: x.replace(" i'm ", " i am "))
    df[column_to_clean] = df[column_to_clean].apply(lambda x: x.replace(" it's ", " it is "))
    df[column_to_clean] = df[column_to_clean].apply(lambda x: x.replace(" she'd ", " she would "))
    df[column_to_clean] = df[column_to_clean].apply(lambda x: x.replace(" she'll ", " she will "))
    df[column_to_clean] = df[column_to_clean].apply(lambda x: x.replace(" we'd ", " we would "))
    df[column_to_clean] = df[column_to_clean].apply(lambda x: x.replace(" we'll ", " we will "))
    df[column_to_clean] = df[column_to_clean].apply(lambda x: x.replace(" we're ", " we are "))
    df[column_to_clean] = df[column_to_clean].apply(lambda x: x.replace(" we've ", " we have "))
    cleaned_tweets = []
    for label in df.index:
        tweet = df.loc[label, :][column_to_clean]
        # tweet = tweet.lower()
        clean = [x for x in tweet.split() if x not in string.punctuation]
        clean = [x for x in clean if x not in nltk_stopwords]
        clean = [x for x in clean if "@" not in x]
        clean = [x for x in clean if "฿" not in x]
        clean = [x for x in clean if x[0] not in string.digits]
        clean = [x for x in clean if x[0] not in remove_punctuaton]
        clean = [x for x in clean if len(x) != 1]
        clean = " ".join(clean)
        clean = clean.strip()
        cleaned_tweets.append(clean)

    df[new_col] = cleaned_tweets

    return df

def contractions(dataframe, column):
    dataframe[column] = dataframe[column].apply(lambda x: x.replace(" aint ", " am not "))
    dataframe[column] = dataframe[column].apply(lambda x: x.replace(" arent ", " are not "))
    dataframe[column] = dataframe[column].apply(lambda x: x.replace(" cant ", " can not "))
    dataframe[column] = dataframe[column].apply(lambda x: x.replace(" couldnt ", " could not "))
    dataframe[column] = dataframe[column].apply(lambda x: x.replace(" couldve ", " could have "))
    dataframe[column] = dataframe[column].apply(lambda x: x.replace(" didnt ", " did not "))
    dataframe[column] = dataframe[column].apply(lambda x: x.replace(" doesnt ", " does not "))
    dataframe[column] = dataframe[column].apply(lambda x: x.replace(" dont ", " do not "))
    dataframe[column] = dataframe[column].apply(lambda x: x.replace(" hadnt ", " had not "))
    dataframe[column] = dataframe[column].apply(lambda x: x.replace(" hasnt ", " has not "))
    dataframe[column] = dataframe[column].apply(lambda x: x.replace(" havent ", " have not "))
    dataframe[column] = dataframe[column].apply(lambda x: x.replace(" hed ", " he would "))
    dataframe[column] = dataframe[column].apply(lambda x: x.replace(" hes ", " he is "))
    dataframe[column] = dataframe[column].apply(lambda x: x.replace(" heres ", " here is "))
    dataframe[column] = dataframe[column].apply(lambda x: x.replace(" howd ", " how did "))
    dataframe[column] = dataframe[column].apply(lambda x: x.replace(" howll ", " how will "))
    dataframe[column] = dataframe[column].apply(lambda x: x.replace(" hows ", " how is "))
    dataframe[column] = dataframe[column].apply(lambda x: x.replace(" im ", " i am "))
    dataframe[column] = dataframe[column].apply(lambda x: x.replace(" ive ", " i have "))
    dataframe[column] = dataframe[column].apply(lambda x: x.replace(" isnt ", " is not "))
    dataframe[column] = dataframe[column].apply(lambda x: x.replace(" it'd ", " it would "))
    dataframe[column] = dataframe[column].apply(lambda x: x.replace(" itll ", " it will "))
    dataframe[column] = dataframe[column].apply(lambda x: x.replace(" lets ", " let us "))
    dataframe[column] = dataframe[column].apply(lambda x: x.replace(" maam ", " madam "))
    dataframe[column] = dataframe[column].apply(lambda x: x.replace(" mightve ", " might have "))
    dataframe[column] = dataframe[column].apply(lambda x: x.replace(" mustve ", " must have "))
    dataframe[column] = dataframe[column].apply(lambda x: x.replace(" neednt ", " need not "))
    dataframe[column] = dataframe[column].apply(lambda x: x.replace(" oughtnt ", " ought not "))
    dataframe[column] = dataframe[column].apply(lambda x: x.replace(" shant ", " shall not "))
    dataframe[column] = dataframe[column].apply(lambda x: x.replace(" shes ", " she is "))
    dataframe[column] = dataframe[column].apply(lambda x: x.replace(" shouldve ", " should have "))
    dataframe[column] = dataframe[column].apply(lambda x: x.replace(" thatd ", " that would "))
    dataframe[column] = dataframe[column].apply(lambda x: x.replace(" theres ", " there is "))
    dataframe[column] = dataframe[column].apply(lambda x: x.replace(" theyd ", " they would "))
    dataframe[column] = dataframe[column].apply(lambda x: x.replace(" theyll ", " they will "))
    dataframe[column] = dataframe[column].apply(lambda x: x.replace(" theyre ", " they are "))
    dataframe[column] = dataframe[column].apply(lambda x: x.replace(" theyve ", " they have "))
    dataframe[column] = dataframe[column].apply(lambda x: x.replace(" wasnt ", " was not "))
    dataframe[column] = dataframe[column].apply(lambda x: x.replace(" werent ", " were not "))
    dataframe[column] = dataframe[column].apply(lambda x: x.replace(" whatll ", " what will "))
    dataframe[column] = dataframe[column].apply(lambda x: x.replace(" whatre ", " what are "))
    dataframe[column] = dataframe[column].apply(lambda x: x.replace(" whatve ", " what have "))
    dataframe[column] = dataframe[column].apply(lambda x: x.replace(" whats ", " what is "))
    dataframe[column] = dataframe[column].apply(lambda x: x.replace(" whens ", " when is "))
    dataframe[column] = dataframe[column].apply(lambda x: x.replace(" whenve ", " when have "))
    dataframe[column] = dataframe[column].apply(lambda x: x.replace(" whered ", " where did "))
    dataframe[column] = dataframe[column].apply(lambda x: x.replace(" wheres ", " where is "))
    dataframe[column] = dataframe[column].apply(lambda x: x.replace(" whereve ", " where have "))
    dataframe[column] = dataframe[column].apply(lambda x: x.replace(" wholl ", " who will "))
    dataframe[column] = dataframe[column].apply(lambda x: x.replace(" whove ", " who have "))
    dataframe[column] = dataframe[column].apply(lambda x: x.replace(" whos ", " who is "))
    dataframe[column] = dataframe[column].apply(lambda x: x.replace(" wont ", " will not "))
    dataframe[column] = dataframe[column].apply(lambda x: x.replace(" whys ", " why is "))
    dataframe[column] = dataframe[column].apply(lambda x: x.replace(" whyve ", " why have "))
    dataframe[column] = dataframe[column].apply(lambda x: x.replace(" wouldve ", " would have "))
    dataframe[column] = dataframe[column].apply(lambda x: x.replace(" wouldnt ", " would not "))
    dataframe[column] = dataframe[column].apply(lambda x: x.replace(" yall ", " you all "))
    dataframe[column] = dataframe[column].apply(lambda x: x.replace(" youd ", " you would "))
    dataframe[column] = dataframe[column].apply(lambda x: x.replace(" youre ", " you are "))
    dataframe[column] = dataframe[column].apply(lambda x: x.replace(" youll ", " you will "))
    dataframe[column] = dataframe[column].apply(lambda x: x.replace(" youve ", " you have "))
    dataframe[column] = dataframe[column].apply(lambda x: x.replace(" youre ", " you are "))


def curse_words(dataframe, column):
    dataframe[column] = dataframe[column].apply(lambda x: x.replace(" fing ", " fucking "))
    dataframe[column] = dataframe[column].apply(lambda x: x.replace(" fu ", " fuck you "))
    dataframe[column] = dataframe[column].apply(lambda x: x.replace(" ill ", " i will "))
    dataframe[column] = dataframe[column].apply(lambda x: x.replace(" id ", " i would "))
    dataframe[column] = dataframe[column].apply(lambda x: x.replace(" theres ", " there is "))

def twitter_words(dataframe, column):
    dataframe[column] = dataframe[column].apply(lambda x: x.replace(' dm ', " direct message "))
    dataframe[column] = dataframe[column].apply(lambda x: x.replace(' pls ', " please "))

    dataframe[column] = dataframe[column].apply(lambda x: x.replace(" cant ", " can not "))
    dataframe[column] = dataframe[column].apply(lambda x: x.replace(" hehe ", ""))
    dataframe[column] = dataframe[column].apply(lambda x: x.replace(" hmm ", ""))
    dataframe[column] = dataframe[column].apply(lambda x: x.replace(" smh ", " shaking my head "))

def airline_words(dataframe, column):
    dataframe[column] = dataframe[column].apply(lambda x: x.replace(' aa ', " american airlines "))
    dataframe[column] = dataframe[column].apply(lambda x: x.replace(' carryon ', " carry on "))
    dataframe[column] = dataframe[column].apply(lambda x: x.replace(' cust ', " customer "))
    dataframe[column] = dataframe[column].apply(lambda x: x.replace(' svc ', " service "))
    dataframe[column] = dataframe[column].apply(lambda x: x.replace(' flightsyr ', " flights "))
    dataframe[column] = dataframe[column].apply(lambda x: x.replace(' servicecomm ', " service and communication "))
    dataframe[column] = dataframe[column].apply(lambda x: x.replace(' nola ', " new orleans "))
    dataframe[column] = dataframe[column].apply(lambda x: x.replace(" conn ", " connecting "))


def filtration_2(dataframe, column):
    # clean = list(map(lambda x: x.replace("#", ""), clean)) #we want to maintain hashtags!
    dataframe[column] = dataframe[column].apply(lambda x: x.replace('"', ""))
    dataframe[column] = dataframe[column].apply(lambda x: x.replace("’", ""))
    dataframe[column] = dataframe[column].apply(lambda x: x.replace("♬♫♩♪", ""))
    dataframe[column] = dataframe[column].apply(lambda x: x.replace("…", ""))
    dataframe[column] = dataframe[column].apply(lambda x: x.replace(".",""))
    dataframe[column] = dataframe[column].apply(lambda x: x.replace("⋆", ""))
    dataframe[column] = dataframe[column].apply(lambda x: x.replace(" ⋆ ", " "))
    dataframe[column] = dataframe[column].apply(lambda x: x.replace("  ", " "))
    dataframe[column] = dataframe[column].apply(lambda x: x.replace("#rt", ""))
    dataframe[column] = dataframe[column].apply(lambda x: x.replace("#re", ""))
    dataframe[column] = dataframe[column].apply(lambda x: x.replace(" alime ", " all time "))
    dataframe[column] = dataframe[column].apply(lambda x: x.replace(" alltime ", " all time "))
    dataframe[column] = dataframe[column].apply(lambda x: x.replace(" →", ""))
    dataframe[column] = dataframe[column].apply(lambda x: x.replace("alime", "all time "))
    dataframe[column] = dataframe[column].apply(lambda x: x.replace("atm", "at the moment"))
    dataframe[column] = dataframe[column].apply(lambda x: x.replace(" ath ", " all time high "))
    dataframe[column] = dataframe[column].apply(lambda x: x.replace("str8", "straight"))
    dataframe[column] = dataframe[column].apply(lambda x: x.replace(" v ", " very "))
    dataframe[column] = dataframe[column].apply(lambda x: x.replace(" #d", ""))
    dataframe[column] = dataframe[column].apply(lambda x: x.replace(" ddos ", " distributed denial of service "))
    dataframe[column] = dataframe[column].apply(lambda x: x.replace("btce", "btc"))
    dataframe[column] = dataframe[column].apply(lambda x: x.replace("bitcoina", "bitcoin"))
    dataframe[column] = dataframe[column].apply(lambda x: x.replace("rbitcoin", "bitcoin"))
    dataframe[column] = dataframe[column].apply(lambda x: x.replace(" – ", " "))
    dataframe[column] = dataframe[column].apply(lambda x: x.replace("-&gt;", ""))
    dataframe[column] = dataframe[column].apply(lambda x: x.replace(" ➤ ", " "))
    dataframe[column] = dataframe[column].apply(lambda x: x.replace("◄►", ""))
    dataframe[column] = dataframe[column].apply(lambda x: x.replace("◄", ""))
    dataframe[column] = dataframe[column].apply(lambda x: x.replace(" ur ", " your "))
    dataframe[column] = dataframe[column].apply(lambda x: x.replace(" u ", " you "))
    dataframe[column] = dataframe[column].apply(lambda x: x.replace("forthen", "for then"))
    dataframe[column] = dataframe[column].apply(lambda x: x.replace("&gt;", "greater than"))
    dataframe[column] = dataframe[column].apply(lambda x: x.replace("&lt;", "less than"))
    dataframe[column] = dataframe[column].apply(lambda x: x.replace("lt", ""))
    dataframe[column] = dataframe[column].apply(lambda x: x.replace("gt", ""))
    dataframe[column] = dataframe[column].apply(lambda x: x.replace(":", ""))
    dataframe[column] = dataframe[column].apply(lambda x: x.replace("&amp;", "and"))
    dataframe[column] = dataframe[column].apply(lambda x: x.replace("ampamp", "and"))
    dataframe[column] = dataframe[column].apply(lambda x: x.replace(" amp ", " and "))
    dataframe[column] = dataframe[column].apply(lambda x: x.replace("amp", "and"))
    dataframe[column] = dataframe[column].apply(lambda x: x.replace(" bu ", " but "))
    dataframe[column] = dataframe[column].apply(lambda x: x.replace("/", ""))
    dataframe[column] = dataframe[column].apply(lambda x: x.replace("...", ""))
    dataframe[column] = dataframe[column].apply(lambda x: x.replace("(", ""))
    dataframe[column] = dataframe[column].apply(lambda x: x.replace(")", ""))
    dataframe[column] = dataframe[column].apply(lambda x: x.replace("“", '"'))
    dataframe[column] = dataframe[column].apply(lambda x: x.replace("”", '"'))
    dataframe[column] = dataframe[column].apply(lambda x: x.replace("‘", ""))
    dataframe[column] = dataframe[column].apply(lambda x: x.replace("’", ""))
    dataframe[column] = dataframe[column].apply(lambda x: x.replace("-"," "))
    dataframe[column] = dataframe[column].apply(lambda x: x.replace("*", ""))
    dataframe[column] = dataframe[column].apply(lambda x: x.replace("!", ""))
    dataframe[column] = dataframe[column].apply(lambda x: x.replace("⬛️", ""))
    dataframe[column] = dataframe[column].apply(lambda x: x.replace("\u200d", ""))
    dataframe[column] = dataframe[column].apply(lambda x: x.replace("\U0001f986", ""))
    dataframe[column] = dataframe[column].apply(lambda x: x.replace("\U0001f942", ""))
    dataframe[column] = dataframe[column].apply(lambda x: x.replace("\U0001f92f", ""))
    dataframe[column] = dataframe[column].apply(lambda x: x.replace("\U0001f911", ""))
    dataframe[column] = dataframe[column].apply(lambda x: x.replace("\U0001F193", ""))
    dataframe[column] = dataframe[column].apply(lambda x: x.replace(" ⭕ ", " "))
    dataframe[column] = dataframe[column].apply(lambda x: x.replace("🤔", ""))
    dataframe[column] = dataframe[column].apply(lambda x: x.replace("☞ ", ""))
    dataframe[column] = dataframe[column].apply(lambda x: x.replace("[", ""))
    dataframe[column] = dataframe[column].apply(lambda x: x.replace("]", ""))
    dataframe[column] = dataframe[column].apply(lambda x: x.replace("{", ""))
    dataframe[column] = dataframe[column].apply(lambda x: x.replace("}", ""))
    dataframe[column] = dataframe[column].apply(lambda x: x.replace("ô", "o"))
    dataframe[column] = dataframe[column].apply(lambda x: x.replace("ó", "o"))
    dataframe[column] = dataframe[column].apply(lambda x: x.replace("é", "e"))
    dataframe[column] = dataframe[column].apply(lambda x: x.replace("ï","i"))
    dataframe[column] = dataframe[column].apply(lambda x: x.replace("®", ""))
    dataframe[column] = dataframe[column].apply(lambda x: x.replace("á", "a"))
    dataframe[column] = dataframe[column].apply(lambda x: x.replace("ã", "a"))
    dataframe[column] = dataframe[column].apply(lambda x: x.replace("ç", "c"))
    dataframe[column] = dataframe[column].apply(lambda x: x.replace(" jan ", " january "))
    dataframe[column] = dataframe[column].apply(lambda x: x.replace(" feb ", " february "))
    dataframe[column] = dataframe[column].apply(lambda x: x.replace(" mar ", " march "))
    dataframe[column] = dataframe[column].apply(lambda x: x.replace(" apr ", " april "))
    dataframe[column] = dataframe[column].apply(lambda x: x.replace(" jun ", " june "))
    dataframe[column] = dataframe[column].apply(lambda x: x.replace(" jul ", " july "))
    dataframe[column] = dataframe[column].apply(lambda x: x.replace(" aug ", " august "))
    dataframe[column] = dataframe[column].apply(lambda x: x.replace(" sept ", " september "))
    dataframe[column] = dataframe[column].apply(lambda x: x.replace(" oct ", " october "))
    dataframe[column] = dataframe[column].apply(lambda x: x.replace(" nov ", " november "))
    dataframe[column] = dataframe[column].apply(lambda x: x.replace(" dec ", " december "))
    dataframe[column] = dataframe[column].apply(lambda x: x.replace(" washinon ", " washington "))
    dataframe[column] = dataframe[column].apply(lambda x: x.replace(" dming ", " direct messaging "))
    dataframe[column] = dataframe[column].apply(lambda x: x.replace(" cust ", " customer "))
    dataframe[column] = dataframe[column].apply(lambda x: x.replace(" wcust ", " with customer "))
    dataframe[column] = dataframe[column].apply(lambda x: x.replace(" cc ", " credit card "))
    dataframe[column] = dataframe[column].apply(lambda x: x.replace(" gopros ", " go pros "))
    dataframe[column] = dataframe[column].apply(lambda x: x.replace(" ultimatelyi ", " ultimately i "))
    dataframe[column] = dataframe[column].apply(lambda x: x.replace(" 1hr ", " one hour "))
    dataframe[column] = dataframe[column].apply(lambda x: x.replace(" rep ", " representative "))
    dataframe[column] = dataframe[column].apply(lambda x: x.replace(" wunited ", " with united "))
    dataframe[column] = dataframe[column].apply(lambda x: x.replace(" mp# ", " mileage plus number "))
    dataframe[column] = dataframe[column].apply(lambda x: x.replace(" hrs ", " hours "))
    dataframe[column] = dataframe[column].apply(lambda x: x.replace(" 4hours ", " four hours "))
    dataframe[column] = dataframe[column].apply(lambda x: x.replace(" laxewr ", " lax ewr "))
    dataframe[column] = dataframe[column].apply(lambda x: x.replace(" iadlax ", " iad lax "))
    dataframe[column] = dataframe[column].apply(lambda x: x.replace(" julystill ", " july still "))
    dataframe[column] = dataframe[column].apply(lambda x: x.replace(" 30mins ", " 30 minutes "))
    dataframe[column] = dataframe[column].apply(lambda x: x.replace(" mins ", " minutes "))
    dataframe[column] = dataframe[column].apply(lambda x: x.replace(" 5hours ", " 5 hours "))
    dataframe[column] = dataframe[column].apply(lambda x: x.replace(" checkhowever ", " check however "))
    dataframe[column] = dataframe[column].apply(lambda x: x.replace(" familyno ", " family "))
    dataframe[column] = dataframe[column].apply(lambda x: x.replace(" 2nd ", " second "))
    dataframe[column] = dataframe[column].apply(lambda x: x.replace(" 6hour ", " six hour "))
    dataframe[column] = dataframe[column].apply(lambda x: x.replace(" cuz ", " because "))
    dataframe[column] = dataframe[column].apply(lambda x: x.replace(" cause ", " because "))
    dataframe[column] = dataframe[column].apply(lambda x: x.replace(" ideabuy ", " idea buy "))
    dataframe[column] = dataframe[column].apply(lambda x: x.replace(" fixem ", " fix them "))
    dataframe[column] = dataframe[column].apply(lambda x: x.replace(" properthey ", " proper they "))
    dataframe[column] = dataframe[column].apply(lambda x: x.replace(" americanair ", " american air "))
    dataframe[column] = dataframe[column].apply(lambda x: x.replace(" yea ", " yes "))
    dataframe[column] = dataframe[column].apply(lambda x: x.replace(" gnteed ", " guaranteed "))
    dataframe[column] = dataframe[column].apply(lambda x: x.replace(" 6mo ", " 6 months "))
    dataframe[column] = dataframe[column].apply(lambda x: x.replace(" believei ", " believe "))
    dataframe[column] = dataframe[column].apply(lambda x: x.replace(" btw ", " by the way "))
    dataframe[column] = dataframe[column].apply(lambda x: x.replace(" intl ", " international "))
    dataframe[column] = dataframe[column].apply(lambda x: x.replace(" thxs ", " thanks "))
    dataframe[column] = dataframe[column].apply(lambda x: x.replace(" plususual ", " plus usual "))
    dataframe[column] = dataframe[column].apply(lambda x: x.replace(" fridaycant ", " friday can not "))
    dataframe[column] = dataframe[column].apply(lambda x: x.replace(" lhr ", " 1 hour "))
    dataframe[column] = dataframe[column].apply(lambda x: x.replace(" wheelsup ", " wheels up "))
    dataframe[column] = dataframe[column].apply(lambda x: x.replace(" tryna ", " try and "))
    dataframe[column] = dataframe[column].apply(lambda x: x.replace(" 2hours ", " 2 hours "))
    dataframe[column] = dataframe[column].apply(lambda x: x.replace(" 1st ", " first "))
    dataframe[column] = dataframe[column].apply(lambda x: x.replace(" creditcard ", " credit card "))
    dataframe[column] = dataframe[column].apply(lambda x: x.replace(" luv ", " love "))
    dataframe[column] = dataframe[column].apply(lambda x: x.replace(" obv ", " obviously "))
    dataframe[column] = dataframe[column].apply(lambda x: x.replace(" patientyou ", " patient you "))
    dataframe[column] = dataframe[column].apply(lambda x: x.replace(" youwe ", " you have "))
    dataframe[column] = dataframe[column].apply(lambda x: x.replace(" uraniumone ", " uranium one "))

def strip_leading_and_trailing_spaces(dataframe, column):
    dataframe[column] = dataframe[column].str.strip()

def hashtags(dataframe, column):
    dataframe[column] = dataframe[column].apply(lambda x: x.replace("#", ""))
